artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/madhusudhanant/Datasets/raw/main/legal_summary.zip
  locate_data_file: artifacts/data_ingestion/legal_summary.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.yaml
  ALL_REQUIRED_FILES: ["test-data", "train-data"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/IN-Abs
  tokenizer_name: t5-small

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/legal_summary
  "model_ckpt": t5-small